name: crypto-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot (paper mode)
        env:
          DRY_RUN: "true"
          EXCHANGE: "binance"
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}

          # Use CryptoCompare for candles on CI to avoid Binance 451
          MARKET_DATA_PROVIDER: "cryptocompare"
          CRYPTOCOMPARE_API_KEY: ${{ secrets.CRYPTOCOMPARE_API_KEY }}

          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SYMBOLS: "BTC/USDT,ETH/USDT"
          TIMEFRAME: "5m"
          BUDGET_USDT: "10000"
        run: |
          python run_bot.py --symbols "$SYMBOLS" --tf "$TIMEFRAME" --budget "$BUDGET_USDT"
